/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_graphics_postfx_PostEffectsPass */

#ifndef _Included_sp_graphics_postfx_PostEffectsPass
#define _Included_sp_graphics_postfx_PostEffectsPass
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_graphics_postfx_PostEffectsPass
	* Method:    bind
	* Signature: (J)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_graphics_postfx_PostEffectsPass_bind
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_postfx_PostEffectsPass
	* Method:    native_renderPass
	* Signature: (JJ)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_postfx_PostEffectsPass_native_1renderPass
		(JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
