/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_sparky4j_core_graphics_Window */

#ifndef _Included_sp_sparky4j_core_graphics_Window
#define _Included_sp_sparky4j_core_graphics_Window
#ifdef __cplusplus
extern "C" {
#endif
#undef sp_sparky4j_core_graphics_Window_MAX_KEYS
#define sp_sparky4j_core_graphics_Window_MAX_KEYS 1024L
#undef sp_sparky4j_core_graphics_Window_MAX_BUTTONS
#define sp_sparky4j_core_graphics_Window_MAX_BUTTONS 32L
	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    bindWindow
	* Signature: (Ljava/lang/String;II)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Window_bindWindow
		(JNIEnv *, jobject, jstring, jint, jint);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    clear
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Window_clear
		(JNIEnv *, jobject);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    update
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Window_update
		(JNIEnv *, jobject);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    closed
	* Signature: ()Z
	*/
	JNIEXPORT jboolean JNICALL Java_sp_sparky4j_core_graphics_Window_closed
		(JNIEnv *, jobject);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    getWidth
	* Signature: ()I
	*/
	JNIEXPORT jint JNICALL Java_sp_sparky4j_core_graphics_Window_getWidth
		(JNIEnv *, jobject);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    getHeight
	* Signature: ()I
	*/
	JNIEXPORT jint JNICALL Java_sp_sparky4j_core_graphics_Window_getHeight
		(JNIEnv *, jobject);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    isKeyPressed
	* Signature: (I)Z
	*/
	JNIEXPORT jboolean JNICALL Java_sp_sparky4j_core_graphics_Window_isKeyPressed
		(JNIEnv *, jobject, jint);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    isMouseButtonPressed
	* Signature: (I)Z
	*/
	JNIEXPORT jboolean JNICALL Java_sp_sparky4j_core_graphics_Window_isMouseButtonPressed
		(JNIEnv *, jobject, jint);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    getMouseX
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_sp_sparky4j_core_graphics_Window_getMouseX
		(JNIEnv *, jobject);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    getMouseY
	* Signature: ()D
	*/
	JNIEXPORT jdouble JNICALL Java_sp_sparky4j_core_graphics_Window_getMouseY
		(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
