/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_sparky4j_core_graphics_Renderable2D */

#ifndef _Included_sp_sparky4j_core_graphics_Renderable2D
#define _Included_sp_sparky4j_core_graphics_Renderable2D
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_sparky4j_core_graphics_Renderable2D
	* Method:    bind
	* Signature: (Lsp/sparky4j/core/maths/Vector3;Lsp/sparky4j/core/maths/Vector2;Lsp/sparky4j/core/maths/Vector4;)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Renderable2D_bind
		(JNIEnv *, jobject, jobject, jobject, jobject);

	/*
	* Class:     sp_sparky4j_core_graphics_Renderable2D
	* Method:    submit
	* Signature: (Lsp/sparky4j/core/graphics/Renderer2D;)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Renderable2D_submit
		(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
