/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_sparky4j_core_FileUtils */

#ifndef _Included_sp_sparky4j_core_FileUtils
#define _Included_sp_sparky4j_core_FileUtils
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_sparky4j_core_FileUtils
	* Method:    read_file
	* Signature: (Ljava/lang/String;)Ljava/lang/String;
	*/
	JNIEXPORT jstring JNICALL Java_sp_sparky4j_core_FileUtils_read_1file
		(JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
