/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_sparky4j_core_maths_Vector2 */

#ifndef _Included_sp_sparky4j_core_maths_Vector2
#define _Included_sp_sparky4j_core_maths_Vector2
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_sparky4j_core_maths_Vector2
	* Method:    bind
	* Signature: (FF)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_maths_Vector2_bind
		(JNIEnv *, jobject, jfloat, jfloat);

	/*
	* Class:     sp_sparky4j_core_maths_Vector2
	* Method:    add
	* Signature: (Lsp/sparky4j/core/maths/Vector2;)Lsp/sparky4j/core/maths/Vector2;
	*/
	JNIEXPORT jobject JNICALL Java_sp_sparky4j_core_maths_Vector2_add
		(JNIEnv *, jobject, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Vector2
	* Method:    subtract
	* Signature: (Lsp/sparky4j/core/maths/Vector2;)Lsp/sparky4j/core/maths/Vector2;
	*/
	JNIEXPORT jobject JNICALL Java_sp_sparky4j_core_maths_Vector2_subtract
		(JNIEnv *, jobject, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Vector2
	* Method:    multiply
	* Signature: (Lsp/sparky4j/core/maths/Vector2;)Lsp/sparky4j/core/maths/Vector2;
	*/
	JNIEXPORT jobject JNICALL Java_sp_sparky4j_core_maths_Vector2_multiply
		(JNIEnv *, jobject, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Vector2
	* Method:    divide
	* Signature: (Lsp/sparky4j/core/maths/Vector2;)Lsp/sparky4j/core/maths/Vector2;
	*/
	JNIEXPORT jobject JNICALL Java_sp_sparky4j_core_maths_Vector2_divide
		(JNIEnv *, jobject, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Vector2
	* Method:    x
	* Signature: ()F
	*/
	JNIEXPORT jfloat JNICALL Java_sp_sparky4j_core_maths_Vector2_x__
		(JNIEnv *, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Vector2
	* Method:    y
	* Signature: ()F
	*/
	JNIEXPORT jfloat JNICALL Java_sp_sparky4j_core_maths_Vector2_y__
		(JNIEnv *, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Vector2
	* Method:    x
	* Signature: (F)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_maths_Vector2_x__F
		(JNIEnv *, jobject, jfloat);

	/*
	* Class:     sp_sparky4j_core_maths_Vector2
	* Method:    y
	* Signature: (F)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_maths_Vector2_y__F
		(JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
