/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_sparky4j_core_GL */

#ifndef _Included_sp_sparky4j_core_GL
#define _Included_sp_sparky4j_core_GL
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_sparky4j_core_GL
	* Method:    glClearColor
	* Signature: (FFFF)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_GL_glClearColor
		(JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

	/*
	* Class:     sp_sparky4j_core_GL
	* Method:    glBegin
	* Signature: (I)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_GL_glBegin
		(JNIEnv *, jclass, jint);

	/*
	* Class:     sp_sparky4j_core_GL
	* Method:    glVertex2f
	* Signature: (FF)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_GL_glVertex2f
		(JNIEnv *, jclass, jfloat, jfloat);

	/*
	* Class:     sp_sparky4j_core_GL
	* Method:    glEnd
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_GL_glEnd
		(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
