/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_sparky4j_core_maths_Vector3 */

#ifndef _Included_sp_sparky4j_core_maths_Vector3
#define _Included_sp_sparky4j_core_maths_Vector3
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_sparky4j_core_maths_Vector3
	* Method:    bind
	* Signature: (FFF)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_maths_Vector3_bind
		(JNIEnv *, jobject, jfloat, jfloat, jfloat);

	/*
	* Class:     sp_sparky4j_core_maths_Vector3
	* Method:    add
	* Signature: (Lsp/sparky4j/core/maths/Vector3;)Lsp/sparky4j/core/maths/Vector3;
	*/
	JNIEXPORT jobject JNICALL Java_sp_sparky4j_core_maths_Vector3_add
		(JNIEnv *, jobject, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Vector3
	* Method:    subtract
	* Signature: (Lsp/sparky4j/core/maths/Vector3;)Lsp/sparky4j/core/maths/Vector3;
	*/
	JNIEXPORT jobject JNICALL Java_sp_sparky4j_core_maths_Vector3_subtract
		(JNIEnv *, jobject, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Vector3
	* Method:    multiply
	* Signature: (Lsp/sparky4j/core/maths/Vector3;)Lsp/sparky4j/core/maths/Vector3;
	*/
	JNIEXPORT jobject JNICALL Java_sp_sparky4j_core_maths_Vector3_multiply
		(JNIEnv *, jobject, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Vector3
	* Method:    divide
	* Signature: (Lsp/sparky4j/core/maths/Vector3;)Lsp/sparky4j/core/maths/Vector3;
	*/
	JNIEXPORT jobject JNICALL Java_sp_sparky4j_core_maths_Vector3_divide
		(JNIEnv *, jobject, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Vector3
	* Method:    x
	* Signature: ()F
	*/
	JNIEXPORT jfloat JNICALL Java_sp_sparky4j_core_maths_Vector3_x__
		(JNIEnv *, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Vector3
	* Method:    y
	* Signature: ()F
	*/
	JNIEXPORT jfloat JNICALL Java_sp_sparky4j_core_maths_Vector3_y__
		(JNIEnv *, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Vector3
	* Method:    z
	* Signature: ()F
	*/
	JNIEXPORT jfloat JNICALL Java_sp_sparky4j_core_maths_Vector3_z__
		(JNIEnv *, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Vector3
	* Method:    x
	* Signature: (F)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_maths_Vector3_x__F
		(JNIEnv *, jobject, jfloat);

	/*
	* Class:     sp_sparky4j_core_maths_Vector3
	* Method:    y
	* Signature: (F)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_maths_Vector3_y__F
		(JNIEnv *, jobject, jfloat);

	/*
	* Class:     sp_sparky4j_core_maths_Vector3
	* Method:    z
	* Signature: (F)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_maths_Vector3_z__F
		(JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
