/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_sparky4j_core_graphics_Simple2DRenderer */

#ifndef _Included_sp_sparky4j_core_graphics_Simple2DRenderer
#define _Included_sp_sparky4j_core_graphics_Simple2DRenderer
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_sparky4j_core_graphics_Simple2DRenderer
	* Method:    bind
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Simple2DRenderer_bind
		(JNIEnv *, jobject);

	/*
	* Class:     sp_sparky4j_core_graphics_Simple2DRenderer
	* Method:    nativeSubmit
	* Signature: (Lsp/sparky4j/core/graphics/Renderable2D;)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Simple2DRenderer_nativeSubmit
		(JNIEnv *, jobject, jobject);

	/*
	* Class:     sp_sparky4j_core_graphics_Simple2DRenderer
	* Method:    nativeFlush
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Simple2DRenderer_nativeFlush
		(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
