/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_sparky4j_core_graphics_StaticSprite */

#ifndef _Included_sp_sparky4j_core_graphics_StaticSprite
#define _Included_sp_sparky4j_core_graphics_StaticSprite
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_sparky4j_core_graphics_StaticSprite
	* Method:    bind
	* Signature: (FFFFLsp/sparky4j/core/maths/Vector4;Lsp/sparky4j/core/graphics/Shader;)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_StaticSprite_bind
		(JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
