/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_sparky4j_core_graphics_Sprite */

#ifndef _Included_sp_sparky4j_core_graphics_Sprite
#define _Included_sp_sparky4j_core_graphics_Sprite
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_sparky4j_core_graphics_Sprite
	* Method:    bind
	* Signature: (FFFFLsp/sparky4j/core/maths/Vector4;)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Sprite_bind__FFFFLsp_sparky4j_core_maths_Vector4_2
		(JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jobject);

	/*
	* Class:     sp_sparky4j_core_graphics_Sprite
	* Method:    bind
	* Signature: (FFFFLsp/sparky4j/core/graphics/Texture;)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Sprite_bind__FFFFLsp_sparky4j_core_graphics_Texture_2
		(JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jobject);

#ifdef __cplusplus
}
#endif
#endif
