/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_sparky4j_core_maths_Vector4 */

#ifndef _Included_sp_sparky4j_core_maths_Vector4
#define _Included_sp_sparky4j_core_maths_Vector4
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_sparky4j_core_maths_Vector4
	* Method:    bind
	* Signature: (FFFF)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_maths_Vector4_bind
		(JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

	/*
	* Class:     sp_sparky4j_core_maths_Vector4
	* Method:    add
	* Signature: (Lsp/sparky4j/core/maths/Vector4;)Lsp/sparky4j/core/maths/Vector4;
	*/
	JNIEXPORT jobject JNICALL Java_sp_sparky4j_core_maths_Vector4_add
		(JNIEnv *, jobject, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Vector4
	* Method:    subtract
	* Signature: (Lsp/sparky4j/core/maths/Vector4;)Lsp/sparky4j/core/maths/Vector4;
	*/
	JNIEXPORT jobject JNICALL Java_sp_sparky4j_core_maths_Vector4_subtract
		(JNIEnv *, jobject, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Vector4
	* Method:    multiply
	* Signature: (Lsp/sparky4j/core/maths/Vector4;)Lsp/sparky4j/core/maths/Vector4;
	*/
	JNIEXPORT jobject JNICALL Java_sp_sparky4j_core_maths_Vector4_multiply
		(JNIEnv *, jobject, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Vector4
	* Method:    divide
	* Signature: (Lsp/sparky4j/core/maths/Vector4;)Lsp/sparky4j/core/maths/Vector4;
	*/
	JNIEXPORT jobject JNICALL Java_sp_sparky4j_core_maths_Vector4_divide
		(JNIEnv *, jobject, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Vector4
	* Method:    x
	* Signature: ()F
	*/
	JNIEXPORT jfloat JNICALL Java_sp_sparky4j_core_maths_Vector4_x__
		(JNIEnv *, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Vector4
	* Method:    y
	* Signature: ()F
	*/
	JNIEXPORT jfloat JNICALL Java_sp_sparky4j_core_maths_Vector4_y__
		(JNIEnv *, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Vector4
	* Method:    z
	* Signature: ()F
	*/
	JNIEXPORT jfloat JNICALL Java_sp_sparky4j_core_maths_Vector4_z__
		(JNIEnv *, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Vector4
	* Method:    w
	* Signature: ()F
	*/
	JNIEXPORT jfloat JNICALL Java_sp_sparky4j_core_maths_Vector4_w__
		(JNIEnv *, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Vector4
	* Method:    x
	* Signature: (F)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_maths_Vector4_x__F
		(JNIEnv *, jobject, jfloat);

	/*
	* Class:     sp_sparky4j_core_maths_Vector4
	* Method:    y
	* Signature: (F)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_maths_Vector4_y__F
		(JNIEnv *, jobject, jfloat);

	/*
	* Class:     sp_sparky4j_core_maths_Vector4
	* Method:    z
	* Signature: (F)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_maths_Vector4_z__F
		(JNIEnv *, jobject, jfloat);

	/*
	* Class:     sp_sparky4j_core_maths_Vector4
	* Method:    w
	* Signature: (F)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_maths_Vector4_w__F
		(JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
