/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_sparky4j_core_maths_Matrix4 */

#ifndef _Included_sp_sparky4j_core_maths_Matrix4
#define _Included_sp_sparky4j_core_maths_Matrix4
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_sparky4j_core_maths_Matrix4
	* Method:    bind
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_maths_Matrix4_bind__
		(JNIEnv *, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Matrix4
	* Method:    bind
	* Signature: (F)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_maths_Matrix4_bind__F
		(JNIEnv *, jobject, jfloat);

	/*
	* Class:     sp_sparky4j_core_maths_Matrix4
	* Method:    multiply
	* Signature: (Lsp/sparky4j/core/maths/Matrix4;)Lsp/sparky4j/core/maths/Matrix4;
	*/
	JNIEXPORT jobject JNICALL Java_sp_sparky4j_core_maths_Matrix4_multiply
		(JNIEnv *, jobject, jobject);

	/*
	* Class:     sp_sparky4j_core_maths_Matrix4
	* Method:    elements
	* Signature: (I)F
	*/
	JNIEXPORT jfloat JNICALL Java_sp_sparky4j_core_maths_Matrix4_elements__I
		(JNIEnv *, jobject, jint);

	/*
	* Class:     sp_sparky4j_core_maths_Matrix4
	* Method:    elements
	* Signature: (IF)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_maths_Matrix4_elements__IF
		(JNIEnv *, jobject, jint, jfloat);

	/*
	* Class:     sp_sparky4j_core_maths_Matrix4
	* Method:    getColumn
	* Signature: (I)Lsp/sparky4j/core/maths/Vector4;
	*/
	JNIEXPORT jobject JNICALL Java_sp_sparky4j_core_maths_Matrix4_getColumn
		(JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
