/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_audio_Sound */

#ifndef _Included_sp_audio_Sound
#define _Included_sp_audio_Sound
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_audio_Sound
	* Method:    bind
	* Signature: (Ljava/lang/String;)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_audio_Sound_bind
		(JNIEnv *, jclass, jstring);

	/*
	* Class:     sp_audio_Sound
	* Method:    native_play
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_audio_Sound_native_1play
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_audio_Sound
	* Method:    native_loop
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_audio_Sound_native_1loop
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_audio_Sound
	* Method:    native_pause
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_audio_Sound_native_1pause
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_audio_Sound
	* Method:    native_resume
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_audio_Sound_native_1resume
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_audio_Sound
	* Method:    native_stop
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_audio_Sound_native_1stop
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_audio_Sound
	* Method:    native_setGain
	* Signature: (JF)V
	*/
	JNIEXPORT void JNICALL Java_sp_audio_Sound_native_1setGain
		(JNIEnv *, jclass, jlong, jfloat);

	/*
	* Class:     sp_audio_Sound
	* Method:    native_isPlaying
	* Signature: (J)Z
	*/
	JNIEXPORT jboolean JNICALL Java_sp_audio_Sound_native_1isPlaying
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_audio_Sound
	* Method:    native_getGain
	* Signature: (J)F
	*/
	JNIEXPORT jfloat JNICALL Java_sp_audio_Sound_native_1getGain
		(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
