/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_audio_SoundManager */

#ifndef _Included_sp_audio_SoundManager
#define _Included_sp_audio_SoundManager
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_audio_SoundManager
	* Method:    init
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_sp_audio_SoundManager_init
		(JNIEnv *, jclass);

	/*
	* Class:     sp_audio_SoundManager
	* Method:    update
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_sp_audio_SoundManager_update
		(JNIEnv *, jclass);

	/*
	* Class:     sp_audio_SoundManager
	* Method:    native_clean
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_sp_audio_SoundManager_native_1clean
		(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
