/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_graphics_Mask */

#ifndef _Included_sp_graphics_Mask
#define _Included_sp_graphics_Mask
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_graphics_Mask
	* Method:    bind
	* Signature: (J[F)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_graphics_Mask_bind
		(JNIEnv *, jclass, jlong, jfloatArray);

	/*
	* Class:     sp_graphics_Mask
	* Method:    native_setTransform
	* Signature: (J[F)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Mask_native_1setTransform
		(JNIEnv *, jclass, jlong, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
