/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_graphics_Framebuffer */

#ifndef _Included_sp_graphics_Framebuffer
#define _Included_sp_graphics_Framebuffer
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_graphics_Framebuffer
	* Method:    bind
	* Signature: (II)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_graphics_Framebuffer_bind
		(JNIEnv *, jclass, jint, jint);

	/*
	* Class:     sp_graphics_Framebuffer
	* Method:    native_bind
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Framebuffer_native_1bind
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Framebuffer
	* Method:    native_clear
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Framebuffer_native_1clear
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Framebuffer
	* Method:    native_getTexture
	* Signature: (J)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_graphics_Framebuffer_native_1getTexture
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Framebuffer
	* Method:    native_setClearColor
	* Signature: (JFFFF)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Framebuffer_native_1setClearColor
		(JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
