/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_graphics_BatchRenderer2D */

#ifndef _Included_sp_graphics_BatchRenderer2D
#define _Included_sp_graphics_BatchRenderer2D
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_graphics_BatchRenderer2D
	* Method:    bind
	* Signature: (II)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_graphics_BatchRenderer2D_bind
		(JNIEnv *, jclass, jint, jint);

	/*
	* Class:     sp_graphics_BatchRenderer2D
	* Method:    native_drawAABB
	* Signature: (JFFFFFFI)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_BatchRenderer2D_native_1drawAABB
		(JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

#ifdef __cplusplus
}
#endif
#endif
