/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_graphics_Font */

#ifndef _Included_sp_graphics_Font
#define _Included_sp_graphics_Font
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_graphics_Font
	* Method:    bind
	* Signature: (Ljava/lang/String;F)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_graphics_Font_bind__Ljava_lang_String_2F
		(JNIEnv *, jclass, jstring, jfloat);

	/*
	* Class:     sp_graphics_Font
	* Method:    bind
	* Signature: ([BIF)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_graphics_Font_bind___3BIF
		(JNIEnv *, jclass, jbyteArray, jint, jfloat);

	/*
	* Class:     sp_graphics_Font
	* Method:    native_setScale
	* Signature: (JFF)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Font_native_1setScale
		(JNIEnv *, jclass, jlong, jfloat, jfloat);

	/*
	* Class:     sp_graphics_Font
	* Method:    native_getID
	* Signature: (J)I
	*/
	JNIEXPORT jint JNICALL Java_sp_graphics_Font_native_1getID
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Font
	* Method:    native_getScaleX
	* Signature: (J)I
	*/
	JNIEXPORT jint JNICALL Java_sp_graphics_Font_native_1getScaleX
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Font
	* Method:    native_getScaleY
	* Signature: (J)I
	*/
	JNIEXPORT jint JNICALL Java_sp_graphics_Font_native_1getScaleY
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Font
	* Method:    native_getSize
	* Signature: (J)I
	*/
	JNIEXPORT jint JNICALL Java_sp_graphics_Font_native_1getSize
		(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
