/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_sparky4j_core_graphics_Texture */

#ifndef _Included_sp_sparky4j_core_graphics_Texture
#define _Included_sp_sparky4j_core_graphics_Texture
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_sparky4j_core_graphics_Texture
	* Method:    bind
	* Signature: (Ljava/lang/String;)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_sparky4j_core_graphics_Texture_bind
		(JNIEnv *, jclass, jstring);

	/*
	* Class:     sp_sparky4j_core_graphics_Texture
	* Method:    native_bind
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Texture_native_1bind
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_sparky4j_core_graphics_Texture
	* Method:    native_unbind
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Texture_native_1unbind
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_sparky4j_core_graphics_Texture
	* Method:    native_getWidth
	* Signature: (J)I
	*/
	JNIEXPORT jint JNICALL Java_sp_sparky4j_core_graphics_Texture_native_1getWidth
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_sparky4j_core_graphics_Texture
	* Method:    native_getHeight
	* Signature: (J)I
	*/
	JNIEXPORT jint JNICALL Java_sp_sparky4j_core_graphics_Texture_native_1getHeight
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_sparky4j_core_graphics_Texture
	* Method:    native_delete
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Texture_native_1delete
		(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
