/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_sparky4j_core_graphics_Renderable2D */

#ifndef _Included_sp_sparky4j_core_graphics_Renderable2D
#define _Included_sp_sparky4j_core_graphics_Renderable2D
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_sparky4j_core_graphics_Renderable2D
	* Method:    bind
	* Signature: (FFFFFI)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_sparky4j_core_graphics_Renderable2D_bind
		(JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

	/*
	* Class:     sp_sparky4j_core_graphics_Renderable2D
	* Method:    native_setColor
	* Signature: (JI)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Renderable2D_native_1setColor__JI
		(JNIEnv *, jclass, jlong, jint);

	/*
	* Class:     sp_sparky4j_core_graphics_Renderable2D
	* Method:    native_setColor
	* Signature: (JFFFF)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Renderable2D_native_1setColor__JFFFF
		(JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

	/*
	* Class:     sp_sparky4j_core_graphics_Renderable2D
	* Method:    native_submit
	* Signature: (JJ)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Renderable2D_native_1submit
		(JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
