/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_sparky4j_core_graphics_Simple2DRenderer */

#ifndef _Included_sp_sparky4j_core_graphics_Simple2DRenderer
#define _Included_sp_sparky4j_core_graphics_Simple2DRenderer
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_sparky4j_core_graphics_Simple2DRenderer
	* Method:    bind
	* Signature: ()J
	*/
	JNIEXPORT jlong JNICALL Java_sp_sparky4j_core_graphics_Simple2DRenderer_bind
		(JNIEnv *, jclass);

	/*
	* Class:     sp_sparky4j_core_graphics_Simple2DRenderer
	* Method:    native_submit
	* Signature: (JJ)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Simple2DRenderer_native_1submit
		(JNIEnv *, jclass, jlong, jlong);

	/*
	* Class:     sp_sparky4j_core_graphics_Simple2DRenderer
	* Method:    native_flush
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Simple2DRenderer_native_1flush
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_sparky4j_core_graphics_Simple2DRenderer
	* Method:    native_push
	* Signature: (J[FZ)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Simple2DRenderer_native_1push
		(JNIEnv *, jclass, jlong, jfloatArray, jboolean);

	/*
	* Class:     sp_sparky4j_core_graphics_Simple2DRenderer
	* Method:    native_pop
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Simple2DRenderer_native_1pop
		(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
