/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_sparky4j_core_graphics_Font */

#ifndef _Included_sp_sparky4j_core_graphics_Font
#define _Included_sp_sparky4j_core_graphics_Font
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_sparky4j_core_graphics_Font
	* Method:    bind
	* Signature: (Ljava/lang/String;Ljava/lang/String;I)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_sparky4j_core_graphics_Font_bind
		(JNIEnv *, jclass, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
