/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_sparky4j_core_graphics_Shader */

#ifndef _Included_sp_sparky4j_core_graphics_Shader
#define _Included_sp_sparky4j_core_graphics_Shader
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_sparky4j_core_graphics_Shader
	* Method:    bind
	* Signature: (Ljava/lang/String;Ljava/lang/String;)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_sparky4j_core_graphics_Shader_bind
		(JNIEnv *, jclass, jstring, jstring);

	/*
	* Class:     sp_sparky4j_core_graphics_Shader
	* Method:    native_setUniform1f
	* Signature: (JLjava/lang/String;F)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Shader_native_1setUniform1f
		(JNIEnv *, jclass, jlong, jstring, jfloat);

	/*
	* Class:     sp_sparky4j_core_graphics_Shader
	* Method:    native_setUniform1fv
	* Signature: (JLjava/lang/String;[FI)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Shader_native_1setUniform1fv
		(JNIEnv *, jclass, jlong, jstring, jfloatArray, jint);

	/*
	* Class:     sp_sparky4j_core_graphics_Shader
	* Method:    native_setUniform1i
	* Signature: (JLjava/lang/String;I)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Shader_native_1setUniform1i
		(JNIEnv *, jclass, jlong, jstring, jint);

	/*
	* Class:     sp_sparky4j_core_graphics_Shader
	* Method:    native_setUniform1iv
	* Signature: (JLjava/lang/String;[II)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Shader_native_1setUniform1iv
		(JNIEnv *, jclass, jlong, jstring, jintArray, jint);

	/*
	* Class:     sp_sparky4j_core_graphics_Shader
	* Method:    native_setUniform2f
	* Signature: (JLjava/lang/String;FF)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Shader_native_1setUniform2f
		(JNIEnv *, jclass, jlong, jstring, jfloat, jfloat);

	/*
	* Class:     sp_sparky4j_core_graphics_Shader
	* Method:    native_setUniform3f
	* Signature: (JLjava/lang/String;FFF)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Shader_native_1setUniform3f
		(JNIEnv *, jclass, jlong, jstring, jfloat, jfloat, jfloat);

	/*
	* Class:     sp_sparky4j_core_graphics_Shader
	* Method:    native_setUniform4f
	* Signature: (JLjava/lang/String;FFFF)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Shader_native_1setUniform4f
		(JNIEnv *, jclass, jlong, jstring, jfloat, jfloat, jfloat, jfloat);

	/*
	* Class:     sp_sparky4j_core_graphics_Shader
	* Method:    native_setUniformMat4
	* Signature: (JLjava/lang/String;[F)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Shader_native_1setUniformMat4
		(JNIEnv *, jclass, jlong, jstring, jfloatArray);

	/*
	* Class:     sp_sparky4j_core_graphics_Shader
	* Method:    native_enable
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Shader_native_1enable
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_sparky4j_core_graphics_Shader
	* Method:    native_disable
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Shader_native_1disable
		(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
