/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_sparky4j_core_graphics_Window */

#ifndef _Included_sp_sparky4j_core_graphics_Window
#define _Included_sp_sparky4j_core_graphics_Window
#ifdef __cplusplus
extern "C" {
#endif
#undef sp_sparky4j_core_graphics_Window_MAX_KEYS
#define sp_sparky4j_core_graphics_Window_MAX_KEYS 1024L
#undef sp_sparky4j_core_graphics_Window_MAX_BUTTONS
#define sp_sparky4j_core_graphics_Window_MAX_BUTTONS 32L
	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    bind
	* Signature: (Ljava/lang/String;II)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_sparky4j_core_graphics_Window_bind
		(JNIEnv *, jclass, jstring, jint, jint);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    native_clear
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Window_native_1clear
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    native_update
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Window_native_1update
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    native_updateInput
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Window_native_1updateInput
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    native_closed
	* Signature: (J)Z
	*/
	JNIEXPORT jboolean JNICALL Java_sp_sparky4j_core_graphics_Window_native_1closed
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    native_isKeyPressed
	* Signature: (JI)Z
	*/
	JNIEXPORT jboolean JNICALL Java_sp_sparky4j_core_graphics_Window_native_1isKeyPressed
		(JNIEnv *, jclass, jlong, jint);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    native_isKeyTyped
	* Signature: (JI)Z
	*/
	JNIEXPORT jboolean JNICALL Java_sp_sparky4j_core_graphics_Window_native_1isKeyTyped
		(JNIEnv *, jclass, jlong, jint);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    native_isMouseButtonPressed
	* Signature: (JI)Z
	*/
	JNIEXPORT jboolean JNICALL Java_sp_sparky4j_core_graphics_Window_native_1isMouseButtonPressed
		(JNIEnv *, jclass, jlong, jint);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    native_isMouseButtonClicked
	* Signature: (JI)Z
	*/
	JNIEXPORT jboolean JNICALL Java_sp_sparky4j_core_graphics_Window_native_1isMouseButtonClicked
		(JNIEnv *, jclass, jlong, jint);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    native_getMouseX
	* Signature: (J)D
	*/
	JNIEXPORT jdouble JNICALL Java_sp_sparky4j_core_graphics_Window_native_1getMouseX
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    native_getMouseY
	* Signature: (J)D
	*/
	JNIEXPORT jdouble JNICALL Java_sp_sparky4j_core_graphics_Window_native_1getMouseY
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    native_get_width
	* Signature: (J)I
	*/
	JNIEXPORT jint JNICALL Java_sp_sparky4j_core_graphics_Window_native_1get_1width
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    native_get_height
	* Signature: (J)I
	*/
	JNIEXPORT jint JNICALL Java_sp_sparky4j_core_graphics_Window_native_1get_1height
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_sparky4j_core_graphics_Window
	* Method:    native_delete
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Window_native_1delete
		(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
