/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_sparky4j_core_graphics_Sprite */

#ifndef _Included_sp_sparky4j_core_graphics_Sprite
#define _Included_sp_sparky4j_core_graphics_Sprite
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_sparky4j_core_graphics_Sprite
	* Method:    bind
	* Signature: (FFFFI)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_sparky4j_core_graphics_Sprite_bind__FFFFI
		(JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jint);

	/*
	* Class:     sp_sparky4j_core_graphics_Sprite
	* Method:    bind
	* Signature: (FFFFJ)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_sparky4j_core_graphics_Sprite_bind__FFFFJ
		(JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jlong);

	/*
	* Class:     sp_sparky4j_core_graphics_Sprite
	* Method:    native_set_position
	* Signature: (JFFF)V
	*/
	JNIEXPORT void JNICALL Java_sp_sparky4j_core_graphics_Sprite_native_1set_1position
		(JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
