/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_utils_Log */

#ifndef _Included_sp_utils_Log
#define _Included_sp_utils_Log
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_utils_Log
	* Method:    SPARKY_FATAL
	* Signature: (Ljava/lang/String;)V
	*/
	JNIEXPORT void JNICALL Java_sp_utils_Log_SPARKY_1FATAL
		(JNIEnv *, jclass, jstring);

	/*
	* Class:     sp_utils_Log
	* Method:    SPARKY_ERROR
	* Signature: (Ljava/lang/String;)V
	*/
	JNIEXPORT void JNICALL Java_sp_utils_Log_SPARKY_1ERROR
		(JNIEnv *, jclass, jstring);

	/*
	* Class:     sp_utils_Log
	* Method:    SPARKY_WARN
	* Signature: (Ljava/lang/String;)V
	*/
	JNIEXPORT void JNICALL Java_sp_utils_Log_SPARKY_1WARN
		(JNIEnv *, jclass, jstring);

	/*
	* Class:     sp_utils_Log
	* Method:    SPARKY_INFO
	* Signature: (Ljava/lang/String;)V
	*/
	JNIEXPORT void JNICALL Java_sp_utils_Log_SPARKY_1INFO
		(JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
