/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itay_wrapper_memory_Memory */

#ifndef _Included_com_itay_wrapper_memory_Memory
#define _Included_com_itay_wrapper_memory_Memory
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_itay_wrapper_memory_Memory
	* Method:    mallocJni
	* Signature: (I)Ljava/nio/ByteBuffer;
	*/
	JNIEXPORT jobject JNICALL Java_com_itay_wrapper_memory_Memory_mallocJni
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_itay_wrapper_memory_Memory
	* Method:    free
	* Signature: (Ljava/nio/Buffer;)V
	*/
	JNIEXPORT void JNICALL Java_com_itay_wrapper_memory_Memory_free
		(JNIEnv *, jclass, jobject);

	/*
	* Class:     com_itay_wrapper_memory_Memory
	* Method:    getBufferAddress
	* Signature: (Ljava/nio/Buffer;)J
	*/
	JNIEXPORT jlong JNICALL Java_com_itay_wrapper_memory_Memory_getBufferAddress
		(JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
